[package]
name = "rust_os"
version = "0.1.0"
edition = "2024"
authors = ["Unterweger Konstantin <konstantin.Unterweger@gmail.com>", "KÃ¶ppl Michael <michael@koeppl.dev>", "Loidolt Lukas <>", "Pritzl Johannes Benedikt <>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"
spin = "0.9.4"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[[bin]]
name = "rust_os"
test = false
bench = false
