[unstable]
build-std-features=["compiler-builtins-mem"]
build-std=["core", "compiler_builtins"]

[build]
target = "x86_64-LL-2025.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
